use std::sync::OnceLock;
use crate::website::model::CountryData;
static LOCAL_COUNTRIES: OnceLock<Vec<CountryData>> = OnceLock::new();

pub fn get_local_countries() -> &'static Vec<CountryData> {
    LOCAL_COUNTRIES.get_or_init(||{
        vec![
            CountryData {
                idalpha3: "AFG".to_string(),
                idalpha2: "AF".to_string(),
                tiene_edos: 1,
                id_pais: 1,
                cad_nombre_es: "Afganistán".to_string(),
            },
            CountryData {
                idalpha3: "ALB".to_string(),
                idalpha2: "AL".to_string(),
                tiene_edos: 1,
                id_pais: 2,
                cad_nombre_es: "Albania".to_string(),
            },
            CountryData {
                idalpha3: "DEU".to_string(),
                idalpha2: "DE".to_string(),
                tiene_edos: 1,
                id_pais: 82,
                cad_nombre_es: "Alemania".to_string(),
            },
            CountryData {
                idalpha3: "AND".to_string(),
                idalpha2: "AD".to_string(),
                tiene_edos: 1,
                id_pais: 5,
                cad_nombre_es: "Andorra".to_string(),
            },
            CountryData {
                idalpha3: "AGO".to_string(),
                idalpha2: "AO".to_string(),
                tiene_edos: 1,
                id_pais: 6,
                cad_nombre_es: "Angola".to_string(),
            },
            CountryData {
                idalpha3: "AIA".to_string(),
                idalpha2: "AI".to_string(),
                tiene_edos: 0,
                id_pais: 7,
                cad_nombre_es: "Anguilla".to_string(),
            },
            CountryData {
                idalpha3: "ATA".to_string(),
                idalpha2: "AQ".to_string(),
                tiene_edos: 0,
                id_pais: 8,
                cad_nombre_es: "Antártida".to_string(),
            },
            CountryData {
                idalpha3: "ATG".to_string(),
                idalpha2: "AG".to_string(),
                tiene_edos: 0,
                id_pais: 9,
                cad_nombre_es: "Antigua y Barbuda".to_string(),
            },
            CountryData {
                idalpha3: "APA".to_string(),
                idalpha2: "AP".to_string(),
                tiene_edos: 0,
                id_pais: 254,
                cad_nombre_es: "Apatrida".to_string(),
            },
            CountryData {
                idalpha3: "SAU".to_string(),
                idalpha2: "SA".to_string(),
                tiene_edos: 1,
                id_pais: 191,
                cad_nombre_es: "Arabia Saudíta".to_string(),
            },
            CountryData {
                idalpha3: "DZA".to_string(),
                idalpha2: "DZ".to_string(),
                tiene_edos: 1,
                id_pais: 3,
                cad_nombre_es: "Argelia".to_string(),
            },
            CountryData {
                idalpha3: "ARG".to_string(),
                idalpha2: "AR".to_string(),
                tiene_edos: 1,
                id_pais: 10,
                cad_nombre_es: "Argentina".to_string(),
            },
            CountryData {
                idalpha3: "ARM".to_string(),
                idalpha2: "AM".to_string(),
                tiene_edos: 1,
                id_pais: 11,
                cad_nombre_es: "Armenia".to_string(),
            },
            CountryData {
                idalpha3: "ABW".to_string(),
                idalpha2: "AW".to_string(),
                tiene_edos: 1,
                id_pais: 12,
                cad_nombre_es: "Aruba".to_string(),
            },
            CountryData {
                idalpha3: "AUS".to_string(),
                idalpha2: "AU".to_string(),
                tiene_edos: 1,
                id_pais: 13,
                cad_nombre_es: "Australia".to_string(),
            },
            CountryData {
                idalpha3: "AUT".to_string(),
                idalpha2: "AT".to_string(),
                tiene_edos: 1,
                id_pais: 14,
                cad_nombre_es: "Austria".to_string(),
            },
            CountryData {
                idalpha3: "AZE".to_string(),
                idalpha2: "AZ".to_string(),
                tiene_edos: 1,
                id_pais: 15,
                cad_nombre_es: "Azerbaiján".to_string(),
            },
            CountryData {
                idalpha3: "BHS".to_string(),
                idalpha2: "BS".to_string(),
                tiene_edos: 1,
                id_pais: 16,
                cad_nombre_es: "Bahamas".to_string(),
            },
            CountryData {
                idalpha3: "BHR".to_string(),
                idalpha2: "BH".to_string(),
                tiene_edos: 0,
                id_pais: 17,
                cad_nombre_es: "Bahrein".to_string(),
            },
            CountryData {
                idalpha3: "BGD".to_string(),
                idalpha2: "BD".to_string(),
                tiene_edos: 1,
                id_pais: 18,
                cad_nombre_es: "Bangladesh".to_string(),
            },
            CountryData {
                idalpha3: "BRB".to_string(),
                idalpha2: "BB".to_string(),
                tiene_edos: 1,
                id_pais: 19,
                cad_nombre_es: "Barbados".to_string(),
            },
            CountryData {
                idalpha3: "BEL".to_string(),
                idalpha2: "BE".to_string(),
                tiene_edos: 1,
                id_pais: 21,
                cad_nombre_es: "Bélgica".to_string(),
            },
            CountryData {
                idalpha3: "BLZ".to_string(),
                idalpha2: "BZ".to_string(),
                tiene_edos: 1,
                id_pais: 22,
                cad_nombre_es: "Belice".to_string(),
            },
            CountryData {
                idalpha3: "BEN".to_string(),
                idalpha2: "BJ".to_string(),
                tiene_edos: 0,
                id_pais: 23,
                cad_nombre_es: "Benín".to_string(),
            },
            CountryData {
                idalpha3: "BMU".to_string(),
                idalpha2: "BM".to_string(),
                tiene_edos: 0,
                id_pais: 24,
                cad_nombre_es: "Bermuda".to_string(),
            },
            CountryData {
                idalpha3: "BTN".to_string(),
                idalpha2: "BT".to_string(),
                tiene_edos: 0,
                id_pais: 25,
                cad_nombre_es: "Bhután".to_string(),
            },
            CountryData {
                idalpha3: "BLR".to_string(),
                idalpha2: "BY".to_string(),
                tiene_edos: 0,
                id_pais: 20,
                cad_nombre_es: "Bielorrusia".to_string(),
            },
            CountryData {
                idalpha3: "BOL".to_string(),
                idalpha2: "BO".to_string(),
                tiene_edos: 1,
                id_pais: 26,
                cad_nombre_es: "Bolivia".to_string(),
            },
            CountryData {
                idalpha3: "BIH".to_string(),
                idalpha2: "BA".to_string(),
                tiene_edos: 1,
                id_pais: 27,
                cad_nombre_es: "Bosnia - Herzegovina".to_string(),
            },
            CountryData {
                idalpha3: "BWA".to_string(),
                idalpha2: "BW".to_string(),
                tiene_edos: 0,
                id_pais: 28,
                cad_nombre_es: "Botswana".to_string(),
            },
            CountryData {
                idalpha3: "BRA".to_string(),
                idalpha2: "BR".to_string(),
                tiene_edos: 1,
                id_pais: 30,
                cad_nombre_es: "Brasil".to_string(),
            },
            CountryData {
                idalpha3: "BRN".to_string(),
                idalpha2: "BN".to_string(),
                tiene_edos: 0,
                id_pais: 32,
                cad_nombre_es: "Brunéi".to_string(),
            },
            CountryData {
                idalpha3: "BGR".to_string(),
                idalpha2: "BG".to_string(),
                tiene_edos: 1,
                id_pais: 33,
                cad_nombre_es: "Bulgaria".to_string(),
            },
            CountryData {
                idalpha3: "BFA".to_string(),
                idalpha2: "BF".to_string(),
                tiene_edos: 1,
                id_pais: 34,
                cad_nombre_es: "Burkina Faso".to_string(),
            },
            CountryData {
                idalpha3: "BUR".to_string(),
                idalpha2: "BU".to_string(),
                tiene_edos: 0,
                id_pais: 253,
                cad_nombre_es: "Burma".to_string(),
            },
            CountryData {
                idalpha3: "BDI".to_string(),
                idalpha2: "BI".to_string(),
                tiene_edos: 0,
                id_pais: 35,
                cad_nombre_es: "Burundi".to_string(),
            },
            CountryData {
                idalpha3: "CPV".to_string(),
                idalpha2: "CV".to_string(),
                tiene_edos: 0,
                id_pais: 39,
                cad_nombre_es: "Cabo Verde".to_string(),
            },
            CountryData {
                idalpha3: "KHM".to_string(),
                idalpha2: "KH".to_string(),
                tiene_edos: 1,
                id_pais: 36,
                cad_nombre_es: "Camboya".to_string(),
            },
            CountryData {
                idalpha3: "CMR".to_string(),
                idalpha2: "CM".to_string(),
                tiene_edos: 1,
                id_pais: 37,
                cad_nombre_es: "Camerún".to_string(),
            },
            CountryData {
                idalpha3: "CAN".to_string(),
                idalpha2: "CA".to_string(),
                tiene_edos: 1,
                id_pais: 38,
                cad_nombre_es: "Canadá".to_string(),
            },
            CountryData {
                idalpha3: "TCD".to_string(),
                idalpha2: "TD".to_string(),
                tiene_edos: 0,
                id_pais: 42,
                cad_nombre_es: "Chad".to_string(),
            },
            CountryData {
                idalpha3: "CHL".to_string(),
                idalpha2: "CL".to_string(),
                tiene_edos: 1,
                id_pais: 43,
                cad_nombre_es: "Chile".to_string(),
            },
            CountryData {
                idalpha3: "CHN".to_string(),
                idalpha2: "CN".to_string(),
                tiene_edos: 1,
                id_pais: 44,
                cad_nombre_es: "China".to_string(),
            },
            CountryData {
                idalpha3: "CYP".to_string(),
                idalpha2: "CY".to_string(),
                tiene_edos: 1,
                id_pais: 56,
                cad_nombre_es: "Chipre".to_string(),
            },
            CountryData {
                idalpha3: "COL".to_string(),
                idalpha2: "CO".to_string(),
                tiene_edos: 1,
                id_pais: 47,
                cad_nombre_es: "Colombia".to_string(),
            },
            CountryData {
                idalpha3: "CBL".to_string(),
                idalpha2: "CB".to_string(),
                tiene_edos: 0,
                id_pais: 255,
                cad_nombre_es: "Colombian Cays".to_string(),
            },
            CountryData {
                idalpha3: "COM".to_string(),
                idalpha2: "KM".to_string(),
                tiene_edos: 0,
                id_pais: 48,
                cad_nombre_es: "Comoras".to_string(),
            },
            CountryData {
                idalpha3: "COG".to_string(),
                idalpha2: "CG".to_string(),
                tiene_edos: 0,
                id_pais: 49,
                cad_nombre_es: "Congo (Rep.)".to_string(),
            },
            CountryData {
                idalpha3: "KOR".to_string(),
                idalpha2: "KR".to_string(),
                tiene_edos: 1,
                id_pais: 116,
                cad_nombre_es: "Corea del Sur".to_string(),
            },
            CountryData {
                idalpha3: "PRK".to_string(),
                idalpha2: "KP".to_string(),
                tiene_edos: 1,
                id_pais: 115,
                cad_nombre_es: "Corea (Norte)".to_string(),
            },
            CountryData {
                idalpha3: "CIV".to_string(),
                idalpha2: "CI".to_string(),
                tiene_edos: 1,
                id_pais: 53,
                cad_nombre_es: "Costa de Marfil".to_string(),
            },
            CountryData {
                idalpha3: "CRI".to_string(),
                idalpha2: "CR".to_string(),
                tiene_edos: 1,
                id_pais: 52,
                cad_nombre_es: "Costa Rica".to_string(),
            },
            CountryData {
                idalpha3: "HRV".to_string(),
                idalpha2: "HR".to_string(),
                tiene_edos: 1,
                id_pais: 54,
                cad_nombre_es: "Croacia".to_string(),
            },
            CountryData {
                idalpha3: "CUB".to_string(),
                idalpha2: "CU".to_string(),
                tiene_edos: 1,
                id_pais: 55,
                cad_nombre_es: "Cuba".to_string(),
            },
            CountryData {
                idalpha3: "DNK".to_string(),
                idalpha2: "DK".to_string(),
                tiene_edos: 1,
                id_pais: 58,
                cad_nombre_es: "Dinamarca".to_string(),
            },
            CountryData {
                idalpha3: "DMA".to_string(),
                idalpha2: "DM".to_string(),
                tiene_edos: 0,
                id_pais: 60,
                cad_nombre_es: "Dominica".to_string(),
            },
            CountryData {
                idalpha3: "ECU".to_string(),
                idalpha2: "EC".to_string(),
                tiene_edos: 1,
                id_pais: 63,
                cad_nombre_es: "Ecuador".to_string(),
            },
            CountryData {
                idalpha3: "EGY".to_string(),
                idalpha2: "EG".to_string(),
                tiene_edos: 1,
                id_pais: 64,
                cad_nombre_es: "Egipto".to_string(),
            },
            CountryData {
                idalpha3: "SLV".to_string(),
                idalpha2: "SV".to_string(),
                tiene_edos: 1,
                id_pais: 65,
                cad_nombre_es: "El Salvador".to_string(),
            },
            CountryData {
                idalpha3: "ARE".to_string(),
                idalpha2: "AE".to_string(),
                tiene_edos: 1,
                id_pais: 229,
                cad_nombre_es: "Emiratos Árabes Unidos".to_string(),
            },
            CountryData {
                idalpha3: "ERI".to_string(),
                idalpha2: "ER".to_string(),
                tiene_edos: 0,
                id_pais: 67,
                cad_nombre_es: "Eritrea".to_string(),
            },
            CountryData {
                idalpha3: "SVK".to_string(),
                idalpha2: "SK".to_string(),
                tiene_edos: 0,
                id_pais: 197,
                cad_nombre_es: "Eslovaquia".to_string(),
            },
            CountryData {
                idalpha3: "SVN".to_string(),
                idalpha2: "SI".to_string(),
                tiene_edos: 0,
                id_pais: 198,
                cad_nombre_es: "Eslovenia".to_string(),
            },
            CountryData {
                idalpha3: "ESP".to_string(),
                idalpha2: "ES".to_string(),
                tiene_edos: 1,
                id_pais: 205,
                cad_nombre_es: "España".to_string(),
            },
            CountryData {
                idalpha3: "PSE".to_string(),
                idalpha2: "PS".to_string(),
                tiene_edos: 0,
                id_pais: 168,
                cad_nombre_es: "Estado De Palestina".to_string(),
            },
            CountryData {
                idalpha3: "USA".to_string(),
                idalpha2: "US".to_string(),
                tiene_edos: 1,
                id_pais: 231,
                cad_nombre_es: "Estados Unidos".to_string(),
            },
            CountryData {
                idalpha3: "EST".to_string(),
                idalpha2: "EE".to_string(),
                tiene_edos: 1,
                id_pais: 68,
                cad_nombre_es: "Estonia".to_string(),
            },
            CountryData {
                idalpha3: "ETH".to_string(),
                idalpha2: "ET".to_string(),
                tiene_edos: 1,
                id_pais: 69,
                cad_nombre_es: "Etiopía".to_string(),
            },
            CountryData {
                idalpha3: "FJI".to_string(),
                idalpha2: "FJ".to_string(),
                tiene_edos: 0,
                id_pais: 73,
                cad_nombre_es: "Fiji".to_string(),
            },
            CountryData {
                idalpha3: "PHL".to_string(),
                idalpha2: "PH".to_string(),
                tiene_edos: 1,
                id_pais: 173,
                cad_nombre_es: "Filipinas".to_string(),
            },
            CountryData {
                idalpha3: "FIN".to_string(),
                idalpha2: "FI".to_string(),
                tiene_edos: 1,
                id_pais: 74,
                cad_nombre_es: "Finlandia".to_string(),
            },
            CountryData {
                idalpha3: "FXX".to_string(),
                idalpha2: "FX".to_string(),
                tiene_edos: 0,
                id_pais: 256,
                cad_nombre_es: "France, metropolitan".to_string(),
            },
            CountryData {
                idalpha3: "FRA".to_string(),
                idalpha2: "FR".to_string(),
                tiene_edos: 1,
                id_pais: 75,
                cad_nombre_es: "Francia".to_string(),
            },
            CountryData {
                idalpha3: "GAB".to_string(),
                idalpha2: "GA".to_string(),
                tiene_edos: 0,
                id_pais: 79,
                cad_nombre_es: "Gabón".to_string(),
            },
            CountryData {
                idalpha3: "GMB".to_string(),
                idalpha2: "GM".to_string(),
                tiene_edos: 1,
                id_pais: 80,
                cad_nombre_es: "Gambia".to_string(),
            },
            CountryData {
                idalpha3: "GEO".to_string(),
                idalpha2: "GE".to_string(),
                tiene_edos: 0,
                id_pais: 81,
                cad_nombre_es: "Georgia".to_string(),
            },
            CountryData {
                idalpha3: "GHA".to_string(),
                idalpha2: "GH".to_string(),
                tiene_edos: 1,
                id_pais: 83,
                cad_nombre_es: "Ghana".to_string(),
            },
            CountryData {
                idalpha3: "GIB".to_string(),
                idalpha2: "GI".to_string(),
                tiene_edos: 0,
                id_pais: 84,
                cad_nombre_es: "Gibraltar".to_string(),
            },
            CountryData {
                idalpha3: "GRD".to_string(),
                idalpha2: "GD".to_string(),
                tiene_edos: 0,
                id_pais: 87,
                cad_nombre_es: "Granada".to_string(),
            },
            CountryData {
                idalpha3: "GRC".to_string(),
                idalpha2: "GR".to_string(),
                tiene_edos: 1,
                id_pais: 85,
                cad_nombre_es: "Grecia".to_string(),
            },
            CountryData {
                idalpha3: "GRL".to_string(),
                idalpha2: "GL".to_string(),
                tiene_edos: 0,
                id_pais: 86,
                cad_nombre_es: "Groenlandia".to_string(),
            },
            CountryData {
                idalpha3: "GLP".to_string(),
                idalpha2: "GP".to_string(),
                tiene_edos: 0,
                id_pais: 88,
                cad_nombre_es: "Guadalupe".to_string(),
            },
            CountryData {
                idalpha3: "GTM".to_string(),
                idalpha2: "GT".to_string(),
                tiene_edos: 1,
                id_pais: 90,
                cad_nombre_es: "Guatemala".to_string(),
            },
            CountryData {
                idalpha3: "GGY".to_string(),
                idalpha2: "GG".to_string(),
                tiene_edos: 0,
                id_pais: 91,
                cad_nombre_es: "Guernsey".to_string(),
            },
            CountryData {
                idalpha3: "GIN".to_string(),
                idalpha2: "GN".to_string(),
                tiene_edos: 0,
                id_pais: 92,
                cad_nombre_es: "Guinea".to_string(),
            },
            CountryData {
                idalpha3: "GNB".to_string(),
                idalpha2: "GW".to_string(),
                tiene_edos: 0,
                id_pais: 93,
                cad_nombre_es: "Guinea-Bissau".to_string(),
            },
            CountryData {
                idalpha3: "GNQ".to_string(),
                idalpha2: "GQ".to_string(),
                tiene_edos: 0,
                id_pais: 66,
                cad_nombre_es: "Guinea Ecuatorial".to_string(),
            },
            CountryData {
                idalpha3: "GUY".to_string(),
                idalpha2: "GY".to_string(),
                tiene_edos: 1,
                id_pais: 94,
                cad_nombre_es: "Guyana".to_string(),
            },
            CountryData {
                idalpha3: "GUF".to_string(),
                idalpha2: "GF".to_string(),
                tiene_edos: 0,
                id_pais: 76,
                cad_nombre_es: "Guyana Francesa".to_string(),
            },
            CountryData {
                idalpha3: "HTI".to_string(),
                idalpha2: "HT".to_string(),
                tiene_edos: 1,
                id_pais: 95,
                cad_nombre_es: "Haití".to_string(),
            },
            CountryData {
                idalpha3: "NLD".to_string(),
                idalpha2: "NL".to_string(),
                tiene_edos: 0,
                id_pais: 259,
                cad_nombre_es: "Holanda".to_string(),
            },
            CountryData {
                idalpha3: "HND".to_string(),
                idalpha2: "HN".to_string(),
                tiene_edos: 1,
                id_pais: 97,
                cad_nombre_es: "Honduras".to_string(),
            },
            CountryData {
                idalpha3: "HUN".to_string(),
                idalpha2: "HU".to_string(),
                tiene_edos: 1,
                id_pais: 99,
                cad_nombre_es: "Hungría".to_string(),
            },
            CountryData {
                idalpha3: "IND".to_string(),
                idalpha2: "IN".to_string(),
                tiene_edos: 1,
                id_pais: 101,
                cad_nombre_es: "India".to_string(),
            },
            CountryData {
                idalpha3: "IDN".to_string(),
                idalpha2: "ID".to_string(),
                tiene_edos: 1,
                id_pais: 102,
                cad_nombre_es: "Indonesia".to_string(),
            },
            CountryData {
                idalpha3: "IRN".to_string(),
                idalpha2: "IR".to_string(),
                tiene_edos: 1,
                id_pais: 103,
                cad_nombre_es: "Irán".to_string(),
            },
            CountryData {
                idalpha3: "IRQ".to_string(),
                idalpha2: "IQ".to_string(),
                tiene_edos: 1,
                id_pais: 104,
                cad_nombre_es: "Iraq".to_string(),
            },
            CountryData {
                idalpha3: "IRL".to_string(),
                idalpha2: "IE".to_string(),
                tiene_edos: 1,
                id_pais: 105,
                cad_nombre_es: "Irlanda".to_string(),
            },
            CountryData {
                idalpha3: "IMN".to_string(),
                idalpha2: "IM".to_string(),
                tiene_edos: 0,
                id_pais: 136,
                cad_nombre_es: "Isla de Man".to_string(),
            },
            CountryData {
                idalpha3: "ISL".to_string(),
                idalpha2: "IS".to_string(),
                tiene_edos: 0,
                id_pais: 100,
                cad_nombre_es: "Islandia".to_string(),
            },
            CountryData {
                idalpha3: "NFK".to_string(),
                idalpha2: "NF".to_string(),
                tiene_edos: 0,
                id_pais: 162,
                cad_nombre_es: "Isla Norfolk".to_string(),
            },
            CountryData {
                idalpha3: "CCK".to_string(),
                idalpha2: "CC".to_string(),
                tiene_edos: 0,
                id_pais: 46,
                cad_nombre_es: "Islas Cocos".to_string(),
            },
            CountryData {
                idalpha3: "COK".to_string(),
                idalpha2: "CK".to_string(),
                tiene_edos: 0,
                id_pais: 51,
                cad_nombre_es: "Islas Cook".to_string(),
            },
            CountryData {
                idalpha3: "FRO".to_string(),
                idalpha2: "FO".to_string(),
                tiene_edos: 0,
                id_pais: 72,
                cad_nombre_es: "Islas Feroe".to_string(),
            },
            CountryData {
                idalpha3: "MNP".to_string(),
                idalpha2: "MP".to_string(),
                tiene_edos: 0,
                id_pais: 163,
                cad_nombre_es: "Islas Marianas".to_string(),
            },
            CountryData {
                idalpha3: "MHL".to_string(),
                idalpha2: "MH".to_string(),
                tiene_edos: 0,
                id_pais: 137,
                cad_nombre_es: "Islas Marshall".to_string(),
            },
            CountryData {
                idalpha3: "UMI".to_string(),
                idalpha2: "UM".to_string(),
                tiene_edos: 0,
                id_pais: 232,
                cad_nombre_es: "Islas Menores Y Remotas De Est".to_string(),
            },
            CountryData {
                idalpha3: "SLB".to_string(),
                idalpha2: "SB".to_string(),
                tiene_edos: 0,
                id_pais: 200,
                cad_nombre_es: "Islas Salomón".to_string(),
            },
            CountryData {
                idalpha3: "ISR".to_string(),
                idalpha2: "IL".to_string(),
                tiene_edos: 1,
                id_pais: 106,
                cad_nombre_es: "Israel".to_string(),
            },
            CountryData {
                idalpha3: "ITA".to_string(),
                idalpha2: "IT".to_string(),
                tiene_edos: 1,
                id_pais: 107,
                cad_nombre_es: "Italia".to_string(),
            },
            CountryData {
                idalpha3: "JAM".to_string(),
                idalpha2: "JM".to_string(),
                tiene_edos: 1,
                id_pais: 108,
                cad_nombre_es: "Jamaica".to_string(),
            },
            CountryData {
                idalpha3: "JPN".to_string(),
                idalpha2: "JP".to_string(),
                tiene_edos: 1,
                id_pais: 109,
                cad_nombre_es: "Japón".to_string(),
            },
            CountryData {
                idalpha3: "JEY".to_string(),
                idalpha2: "JE".to_string(),
                tiene_edos: 0,
                id_pais: 110,
                cad_nombre_es: "Jersey".to_string(),
            },
            CountryData {
                idalpha3: "JOR".to_string(),
                idalpha2: "JO".to_string(),
                tiene_edos: 1,
                id_pais: 111,
                cad_nombre_es: "Jordania".to_string(),
            },
            CountryData {
                idalpha3: "KAZ".to_string(),
                idalpha2: "KZ".to_string(),
                tiene_edos: 1,
                id_pais: 112,
                cad_nombre_es: "Kazajistán".to_string(),
            },
            CountryData {
                idalpha3: "KEN".to_string(),
                idalpha2: "KE".to_string(),
                tiene_edos: 1,
                id_pais: 113,
                cad_nombre_es: "Kenia".to_string(),
            },
            CountryData {
                idalpha3: "KGZ".to_string(),
                idalpha2: "KG".to_string(),
                tiene_edos: 0,
                id_pais: 118,
                cad_nombre_es: "Kirguizstán".to_string(),
            },
            CountryData {
                idalpha3: "KIR".to_string(),
                idalpha2: "KI".to_string(),
                tiene_edos: 0,
                id_pais: 114,
                cad_nombre_es: "Kiribati".to_string(),
            },
            CountryData {
                idalpha3: "KWT".to_string(),
                idalpha2: "KW".to_string(),
                tiene_edos: 1,
                id_pais: 117,
                cad_nombre_es: "Kuwait".to_string(),
            },
            CountryData {
                idalpha3: "LAO".to_string(),
                idalpha2: "LA".to_string(),
                tiene_edos: 0,
                id_pais: 119,
                cad_nombre_es: "Laos".to_string(),
            },
            CountryData {
                idalpha3: "LSO".to_string(),
                idalpha2: "LS".to_string(),
                tiene_edos: 0,
                id_pais: 122,
                cad_nombre_es: "Lesotho".to_string(),
            },
            CountryData {
                idalpha3: "LVA".to_string(),
                idalpha2: "LV".to_string(),
                tiene_edos: 1,
                id_pais: 120,
                cad_nombre_es: "Letonia".to_string(),
            },
            CountryData {
                idalpha3: "LBN".to_string(),
                idalpha2: "LB".to_string(),
                tiene_edos: 1,
                id_pais: 121,
                cad_nombre_es: "Líbano".to_string(),
            },
            CountryData {
                idalpha3: "LBR".to_string(),
                idalpha2: "LR".to_string(),
                tiene_edos: 0,
                id_pais: 123,
                cad_nombre_es: "Liberia".to_string(),
            },
            CountryData {
                idalpha3: "LBY".to_string(),
                idalpha2: "LY".to_string(),
                tiene_edos: 1,
                id_pais: 124,
                cad_nombre_es: "Libia".to_string(),
            },
            CountryData {
                idalpha3: "LIE".to_string(),
                idalpha2: "LI".to_string(),
                tiene_edos: 0,
                id_pais: 125,
                cad_nombre_es: "Liechtenstein".to_string(),
            },
            CountryData {
                idalpha3: "LTU".to_string(),
                idalpha2: "LT".to_string(),
                tiene_edos: 1,
                id_pais: 126,
                cad_nombre_es: "Lituania".to_string(),
            },
            CountryData {
                idalpha3: "LUX".to_string(),
                idalpha2: "LU".to_string(),
                tiene_edos: 1,
                id_pais: 127,
                cad_nombre_es: "Luxemburgo".to_string(),
            },
            CountryData {
                idalpha3: "MKD".to_string(),
                idalpha2: "MK".to_string(),
                tiene_edos: 1,
                id_pais: 129,
                cad_nombre_es: "Macedonia, The Former Yugoslav".to_string(),
            },
            CountryData {
                idalpha3: "MDG".to_string(),
                idalpha2: "MG".to_string(),
                tiene_edos: 1,
                id_pais: 130,
                cad_nombre_es: "Madagascar".to_string(),
            },
            CountryData {
                idalpha3: "MYS".to_string(),
                idalpha2: "MY".to_string(),
                tiene_edos: 1,
                id_pais: 132,
                cad_nombre_es: "Malasia".to_string(),
            },
            CountryData {
                idalpha3: "MWI".to_string(),
                idalpha2: "MW".to_string(),
                tiene_edos: 0,
                id_pais: 131,
                cad_nombre_es: "Malawi".to_string(),
            },
            CountryData {
                idalpha3: "MDV".to_string(),
                idalpha2: "MV".to_string(),
                tiene_edos: 1,
                id_pais: 133,
                cad_nombre_es: "Maldivas".to_string(),
            },
            CountryData {
                idalpha3: "MLI".to_string(),
                idalpha2: "ML".to_string(),
                tiene_edos: 1,
                id_pais: 134,
                cad_nombre_es: "Malí".to_string(),
            },
            CountryData {
                idalpha3: "MLT".to_string(),
                idalpha2: "MT".to_string(),
                tiene_edos: 0,
                id_pais: 135,
                cad_nombre_es: "Malta".to_string(),
            },
            CountryData {
                idalpha3: "MAR".to_string(),
                idalpha2: "MA".to_string(),
                tiene_edos: 1,
                id_pais: 148,
                cad_nombre_es: "Marruecos".to_string(),
            },
            CountryData {
                idalpha3: "MTQ".to_string(),
                idalpha2: "MQ".to_string(),
                tiene_edos: 0,
                id_pais: 138,
                cad_nombre_es: "Martinica".to_string(),
            },
            CountryData {
                idalpha3: "MUS".to_string(),
                idalpha2: "MU".to_string(),
                tiene_edos: 0,
                id_pais: 140,
                cad_nombre_es: "Mauricio".to_string(),
            },
            CountryData {
                idalpha3: "MRT".to_string(),
                idalpha2: "MR".to_string(),
                tiene_edos: 0,
                id_pais: 139,
                cad_nombre_es: "Mauritania".to_string(),
            },
            CountryData {
                idalpha3: "MYT".to_string(),
                idalpha2: "YT".to_string(),
                tiene_edos: 0,
                id_pais: 141,
                cad_nombre_es: "Mayotte".to_string(),
            },
            CountryData {
                idalpha3: "MEX".to_string(),
                idalpha2: "MX".to_string(),
                tiene_edos: 1,
                id_pais: 142,
                cad_nombre_es: "México".to_string(),
            },
            CountryData {
                idalpha3: "FSM".to_string(),
                idalpha2: "FM".to_string(),
                tiene_edos: 0,
                id_pais: 143,
                cad_nombre_es: "Micronesia".to_string(),
            },
            CountryData {
                idalpha3: "MDA".to_string(),
                idalpha2: "MD".to_string(),
                tiene_edos: 0,
                id_pais: 144,
                cad_nombre_es: "Moldavia".to_string(),
            },
            CountryData {
                idalpha3: "MCO".to_string(),
                idalpha2: "MC".to_string(),
                tiene_edos: 0,
                id_pais: 145,
                cad_nombre_es: "Mónaco".to_string(),
            },
            CountryData {
                idalpha3: "MNG".to_string(),
                idalpha2: "MN".to_string(),
                tiene_edos: 0,
                id_pais: 146,
                cad_nombre_es: "Mongolia".to_string(),
            },
            CountryData {
                idalpha3: "MNE".to_string(),
                idalpha2: "ME".to_string(),
                tiene_edos: 0,
                id_pais: 248,
                cad_nombre_es: "Montenegro".to_string(),
            },
            CountryData {
                idalpha3: "MSR".to_string(),
                idalpha2: "MS".to_string(),
                tiene_edos: 0,
                id_pais: 147,
                cad_nombre_es: "Montserrat".to_string(),
            },
            CountryData {
                idalpha3: "MOZ".to_string(),
                idalpha2: "MZ".to_string(),
                tiene_edos: 0,
                id_pais: 149,
                cad_nombre_es: "Mozambique".to_string(),
            },
            CountryData {
                idalpha3: "MMR".to_string(),
                idalpha2: "MM".to_string(),
                tiene_edos: 0,
                id_pais: 150,
                cad_nombre_es: "Myanmar (Birmania)".to_string(),
            },
            CountryData {
                idalpha3: "NAM".to_string(),
                idalpha2: "NA".to_string(),
                tiene_edos: 0,
                id_pais: 151,
                cad_nombre_es: "Namibia".to_string(),
            },
            CountryData {
                idalpha3: "NRU".to_string(),
                idalpha2: "NR".to_string(),
                tiene_edos: 0,
                id_pais: 152,
                cad_nombre_es: "Nauru".to_string(),
            },
            CountryData {
                idalpha3: "NPL".to_string(),
                idalpha2: "NP".to_string(),
                tiene_edos: 0,
                id_pais: 153,
                cad_nombre_es: "Nepal".to_string(),
            },
            CountryData {
                idalpha3: "NIC".to_string(),
                idalpha2: "NI".to_string(),
                tiene_edos: 1,
                id_pais: 158,
                cad_nombre_es: "Nicaragua".to_string(),
            },
            CountryData {
                idalpha3: "NER".to_string(),
                idalpha2: "NE".to_string(),
                tiene_edos: 0,
                id_pais: 159,
                cad_nombre_es: "Níger".to_string(),
            },
            CountryData {
                idalpha3: "NGA".to_string(),
                idalpha2: "NG".to_string(),
                tiene_edos: 1,
                id_pais: 160,
                cad_nombre_es: "Nigeria".to_string(),
            },
            CountryData {
                idalpha3: "NIU".to_string(),
                idalpha2: "NU".to_string(),
                tiene_edos: 0,
                id_pais: 161,
                cad_nombre_es: "Niue".to_string(),
            },
            CountryData {
                idalpha3: "NOR".to_string(),
                idalpha2: "NO".to_string(),
                tiene_edos: 1,
                id_pais: 164,
                cad_nombre_es: "Noruega".to_string(),
            },
            CountryData {
                idalpha3: "NZL".to_string(),
                idalpha2: "NZ".to_string(),
                tiene_edos: 1,
                id_pais: 157,
                cad_nombre_es: "Nueva Zelanda".to_string(),
            },
            CountryData {
                idalpha3: "OMN".to_string(),
                idalpha2: "OM".to_string(),
                tiene_edos: 0,
                id_pais: 165,
                cad_nombre_es: "Omán".to_string(),
            },
            CountryData {
                idalpha3: "NLD".to_string(),
                idalpha2: "NL".to_string(),
                tiene_edos: 1,
                id_pais: 155,
                cad_nombre_es: "Países Bajos".to_string(),
            },
            CountryData {
                idalpha3: "PAK".to_string(),
                idalpha2: "PK".to_string(),
                tiene_edos: 1,
                id_pais: 166,
                cad_nombre_es: "Pakistán".to_string(),
            },
            CountryData {
                idalpha3: "PLW".to_string(),
                idalpha2: "PW".to_string(),
                tiene_edos: 0,
                id_pais: 167,
                cad_nombre_es: "Palaos".to_string(),
            },
            CountryData {
                idalpha3: "PAN".to_string(),
                idalpha2: "PA".to_string(),
                tiene_edos: 1,
                id_pais: 169,
                cad_nombre_es: "Panamá".to_string(),
            },
            CountryData {
                idalpha3: "PNG".to_string(),
                idalpha2: "PG".to_string(),
                tiene_edos: 0,
                id_pais: 170,
                cad_nombre_es: "Papúa Nueva Guinea".to_string(),
            },
            CountryData {
                idalpha3: "PRY".to_string(),
                idalpha2: "PY".to_string(),
                tiene_edos: 1,
                id_pais: 171,
                cad_nombre_es: "Paraguay".to_string(),
            },
            CountryData {
                idalpha3: "PER".to_string(),
                idalpha2: "PE".to_string(),
                tiene_edos: 1,
                id_pais: 172,
                cad_nombre_es: "Perú".to_string(),
            },
            CountryData {
                idalpha3: "PCN".to_string(),
                idalpha2: "PN".to_string(),
                tiene_edos: 0,
                id_pais: 174,
                cad_nombre_es: "Pitcairn".to_string(),
            },
            CountryData {
                idalpha3: "PYF".to_string(),
                idalpha2: "PF".to_string(),
                tiene_edos: 0,
                id_pais: 77,
                cad_nombre_es: "Polinesia Francesa".to_string(),
            },
            CountryData {
                idalpha3: "POL".to_string(),
                idalpha2: "PL".to_string(),
                tiene_edos: 1,
                id_pais: 175,
                cad_nombre_es: "Polonia".to_string(),
            },
            CountryData {
                idalpha3: "PRT".to_string(),
                idalpha2: "PT".to_string(),
                tiene_edos: 1,
                id_pais: 176,
                cad_nombre_es: "Portugal".to_string(),
            },
            CountryData {
                idalpha3: "QAT".to_string(),
                idalpha2: "QA".to_string(),
                tiene_edos: 1,
                id_pais: 178,
                cad_nombre_es: "Qatar".to_string(),
            },
            CountryData {
                idalpha3: "GBR".to_string(),
                idalpha2: "GB".to_string(),
                tiene_edos: 1,
                id_pais: 230,
                cad_nombre_es: "Reino Unido".to_string(),
            },
            CountryData {
                idalpha3: "CAF".to_string(),
                idalpha2: "CF".to_string(),
                tiene_edos: 0,
                id_pais: 41,
                cad_nombre_es: "Rep. Centro Africana".to_string(),
            },
            CountryData {
                idalpha3: "COD".to_string(),
                idalpha2: "CD".to_string(),
                tiene_edos: 0,
                id_pais: 50,
                cad_nombre_es: "Rep Dem Del Congo".to_string(),
            },
            CountryData {
                idalpha3: "CZE".to_string(),
                idalpha2: "CZ".to_string(),
                tiene_edos: 1,
                id_pais: 57,
                cad_nombre_es: "República Checa".to_string(),
            },
            CountryData {
                idalpha3: "MDA".to_string(),
                idalpha2: "MD".to_string(),
                tiene_edos: 0,
                id_pais: 260,
                cad_nombre_es: "República De Moldova".to_string(),
            },
            CountryData {
                idalpha3: "DOM".to_string(),
                idalpha2: "DO".to_string(),
                tiene_edos: 1,
                id_pais: 61,
                cad_nombre_es: "República Dominicana".to_string(),
            },
            CountryData {
                idalpha3: "REU".to_string(),
                idalpha2: "RE".to_string(),
                tiene_edos: 0,
                id_pais: 179,
                cad_nombre_es: "Reunión".to_string(),
            },
            CountryData {
                idalpha3: "RWA".to_string(),
                idalpha2: "RW".to_string(),
                tiene_edos: 1,
                id_pais: 182,
                cad_nombre_es: "Ruanda".to_string(),
            },
            CountryData {
                idalpha3: "ROU".to_string(),

                idalpha2: "RO".to_string(),
                tiene_edos: 1,
                id_pais: 180,
                cad_nombre_es: "Rumanía".to_string(),
            },
            CountryData {
                idalpha3: "RUS".to_string(),
                idalpha2: "RU".to_string(),
                tiene_edos: 1,
                id_pais: 181,
                cad_nombre_es: "Rusia".to_string(),
            },
            CountryData {
                idalpha3: "ESH".to_string(),
                idalpha2: "EH".to_string(),
                tiene_edos: 0,
                id_pais: 242,
                cad_nombre_es: "Sahara Occidental".to_string(),
            },
            CountryData {
                idalpha3: "ASM".to_string(),
                idalpha2: "AS".to_string(),
                tiene_edos: 0,
                id_pais: 4,
                cad_nombre_es: "Samoa (Americana)".to_string(),
            },
            CountryData {
                idalpha3: "WSM".to_string(),
                idalpha2: "WS".to_string(),
                tiene_edos: 0,
                id_pais: 188,
                cad_nombre_es: "Samoa (Oeste)".to_string(),
            },
            CountryData {
                idalpha3: "KNA".to_string(),
                idalpha2: "KN".to_string(),
                tiene_edos: 0,
                id_pais: 184,
                cad_nombre_es: "San Cristóbal y Nieves".to_string(),
            },
            CountryData {
                idalpha3: "SMR".to_string(),
                idalpha2: "SM".to_string(),
                tiene_edos: 0,
                id_pais: 189,
                cad_nombre_es: "San Marino".to_string(),
            },
            CountryData {
                idalpha3: "SHN".to_string(),
                idalpha2: "SH".to_string(),
                tiene_edos: 0,
                id_pais: 183,
                cad_nombre_es: "Santa Elena".to_string(),
            },
            CountryData {
                idalpha3: "LCA".to_string(),
                idalpha2: "LC".to_string(),
                tiene_edos: 1,
                id_pais: 185,
                cad_nombre_es: "Santa Lucía".to_string(),
            },
            CountryData {
                idalpha3: "STP".to_string(),
                idalpha2: "ST".to_string(),
                tiene_edos: 0,
                id_pais: 190,
                cad_nombre_es: "Santo Tomé - Principe".to_string(),
            },
            CountryData {
                idalpha3: "VCT".to_string(),
                idalpha2: "VC".to_string(),
                tiene_edos: 0,
                id_pais: 187,
                cad_nombre_es: "San Vicente y las Granadinas".to_string(),
            },
            CountryData {
                idalpha3: "SEN".to_string(),
                idalpha2: "SN".to_string(),
                tiene_edos: 0,
                id_pais: 192,
                cad_nombre_es: "Senegal".to_string(),
            },
            CountryData {
                idalpha3: "SRB".to_string(),
                idalpha2: "RS".to_string(),
                tiene_edos: 1,
                id_pais: 193,
                cad_nombre_es: "Serbia".to_string(),
            },
            CountryData {
                idalpha3: "SYC".to_string(),
                idalpha2: "SC".to_string(),
                tiene_edos: 0,
                id_pais: 194,
                cad_nombre_es: "Seychelles".to_string(),
            },
            CountryData {
                idalpha3: "SLE".to_string(),
                idalpha2: "SL".to_string(),
                tiene_edos: 0,
                id_pais: 195,
                cad_nombre_es: "Sierra Leona".to_string(),
            },
            CountryData {
                idalpha3: "SGP".to_string(),
                idalpha2: "SG".to_string(),
                tiene_edos: 1,
                id_pais: 196,
                cad_nombre_es: "Singapur".to_string(),
            },
            CountryData {
                idalpha3: "SYR".to_string(),
                idalpha2: "SY".to_string(),
                tiene_edos: 0,
                id_pais: 213,
                cad_nombre_es: "Siria".to_string(),
            },
            CountryData {
                idalpha3: "SOM".to_string(),
                idalpha2: "SO".to_string(),
                tiene_edos: 0,
                id_pais: 201,
                cad_nombre_es: "Somalia".to_string(),
            },
            CountryData {
                idalpha3: "LKA".to_string(),
                idalpha2: "LK".to_string(),
                tiene_edos: 1,
                id_pais: 206,
                cad_nombre_es: "Sri lanka".to_string(),
            },
            CountryData {
                idalpha3: "SHN".to_string(),
                idalpha2: "SH".to_string(),
                tiene_edos: 0,
                id_pais: 261,
                cad_nombre_es: "St Helena".to_string(),
            },
            CountryData {
                idalpha3: "KNA".to_string(),
                idalpha2: "KN".to_string(),
                tiene_edos: 0,
                id_pais: 262,
                cad_nombre_es: "St Kitts - Nevis".to_string(),
            },
            CountryData {
                idalpha3: "SPM".to_string(),
                idalpha2: "PM".to_string(),
                tiene_edos: 0,
                id_pais: 186,
                cad_nombre_es: "St Pierre - Miquelon".to_string(),
            },
            CountryData {
                idalpha3: "VCT".to_string(),
                idalpha2: "VC".to_string(),
                tiene_edos: 0,
                id_pais: 258,
                cad_nombre_es: "St Vincent".to_string(),
            },
            CountryData {
                idalpha3: "ZAF".to_string(),
                idalpha2: "ZA".to_string(),
                tiene_edos: 1,
                id_pais: 202,
                cad_nombre_es: "Sudáfrica".to_string(),
            },
            CountryData {
                idalpha3: "SDN".to_string(),
                idalpha2: "SD".to_string(),
                tiene_edos: 0,
                id_pais: 207,
                cad_nombre_es: "Sudán".to_string(),
            },
            CountryData {
                idalpha3: "SSD".to_string(),
                idalpha2: "SS".to_string(),
                tiene_edos: 0,
                id_pais: 204,
                cad_nombre_es: "Sudán del Sur".to_string(),
            },
            CountryData {
                idalpha3: "SWE".to_string(),
                idalpha2: "SE".to_string(),
                tiene_edos: 1,
                id_pais: 211,
                cad_nombre_es: "Suecia".to_string(),
            },
            CountryData {
                idalpha3: "CHE".to_string(),
                idalpha2: "

CH"
                    .to_string(),
                tiene_edos: 1,
                id_pais: 212,
                cad_nombre_es: "Suiza".to_string(),
            },
            CountryData {
                idalpha3: "SUR".to_string(),
                idalpha2: "SR".to_string(),
                tiene_edos: 0,
                id_pais: 208,
                cad_nombre_es: "Surinam".to_string(),
            },
            CountryData {
                idalpha3: "SJM".to_string(),
                idalpha2: "SJ".to_string(),
                tiene_edos: 0,
                id_pais: 209,
                cad_nombre_es: "Svalbard - Jan Mayen".to_string(),
            },
            CountryData {
                idalpha3: "SWZ".to_string(),
                idalpha2: "SZ".to_string(),
                tiene_edos: 0,
                id_pais: 210,
                cad_nombre_es: "Swazilandia".to_string(),
            },
            CountryData {
                idalpha3: "THA".to_string(),
                idalpha2: "TH".to_string(),
                tiene_edos: 1,
                id_pais: 217,
                cad_nombre_es: "Tailandia".to_string(),
            },
            CountryData {
                idalpha3: "TWN".to_string(),
                idalpha2: "TW".to_string(),
                tiene_edos: 1,
                id_pais: 214,
                cad_nombre_es: "Taiwán".to_string(),
            },
            CountryData {
                idalpha3: "TJK".to_string(),
                idalpha2: "TJ".to_string(),
                tiene_edos: 0,
                id_pais: 215,
                cad_nombre_es: "Tajikistan".to_string(),
            },
            CountryData {
                idalpha3: "TZA".to_string(),
                idalpha2: "TZ".to_string(),
                tiene_edos: 0,
                id_pais: 216,
                cad_nombre_es: "Tanzania".to_string(),
            },
            CountryData {
                idalpha3: "IOT".to_string(),
                idalpha2: "IO".to_string(),
                tiene_edos: 0,
                id_pais: 31,
                cad_nombre_es: "Territorio Britanico Del Ocean".to_string(),
            },
            CountryData {
                idalpha3: "PSE".to_string(),
                idalpha2: "PS".to_string(),
                tiene_edos: 0,
                id_pais: 257,
                cad_nombre_es: "Territorio Palestino Ocupado".to_string(),
            },
            CountryData {
                idalpha3: "ATF".to_string(),
                idalpha2: "TF".to_string(),
                tiene_edos: 0,
                id_pais: 78,
                cad_nombre_es: "Territorios Franceses Del Sur".to_string(),
            },
            CountryData {
                idalpha3: "TLS".to_string(),
                idalpha2: "TP".to_string(),
                tiene_edos: 0,
                id_pais: 62,
                cad_nombre_es: "Timor Oriental".to_string(),
            },
            CountryData {
                idalpha3: "TGO".to_string(),
                idalpha2: "TG".to_string(),
                tiene_edos: 0,
                id_pais: 218,
                cad_nombre_es: "Togo".to_string(),
            },
            CountryData {
                idalpha3: "TKL".to_string(),
                idalpha2: "TK".to_string(),
                tiene_edos: 0,
                id_pais: 219,
                cad_nombre_es: "Tokelau".to_string(),
            },
            CountryData {
                idalpha3: "TON".to_string(),
                idalpha2: "TO".to_string(),
                tiene_edos: 0,
                id_pais: 220,
                cad_nombre_es: "Tonga".to_string(),
            },
            CountryData {
                idalpha3: "TTO".to_string(),
                idalpha2: "TT".to_string(),
                tiene_edos: 1,
                id_pais: 221,
                cad_nombre_es: "Trinidad y Tobajo".to_string(),
            },
            CountryData {
                idalpha3: "TUN".to_string(),
                idalpha2: "TN".to_string(),
                tiene_edos: 0,
                id_pais: 222,
                cad_nombre_es: "Tunez".to_string(),
            },
            CountryData {
                idalpha3: "TKM".to_string(),
                idalpha2: "TM".to_string(),
                tiene_edos: 0,
                id_pais: 224,
                cad_nombre_es: "Turkmenistán".to_string(),
            },
            CountryData {
                idalpha3: "TCA".to_string(),
                idalpha2: "TC".to_string(),
                tiene_edos: 0,
                id_pais: 225,
                cad_nombre_es: "Turks - Islas Caicos".to_string(),
            },
            CountryData {
                idalpha3: "TUR".to_string(),
                idalpha2: "TR".to_string(),
                tiene_edos: 1,
                id_pais: 223,
                cad_nombre_es: "Turquía".to_string(),
            },
            CountryData {
                idalpha3: "TUV".to_string(),
                idalpha2: "TV".to_string(),
                tiene_edos: 0,
                id_pais: 226,
                cad_nombre_es: "Tuvalu".to_string(),
            },
            CountryData {
                idalpha3: "UKR".to_string(),
                idalpha2: "UA".to_string(),
                tiene_edos: 1,
                id_pais: 228,
                cad_nombre_es: "Ucrania".to_string(),
            },
            CountryData {
                idalpha3: "UGA".to_string(),
                idalpha2: "UG".to_string(),
                tiene_edos: 0,
                id_pais: 227,
                cad_nombre_es: "Uganda".to_string(),
            },
            CountryData {
                idalpha3: "URY".to_string(),
                idalpha2: "UY".to_string(),
                tiene_edos: 1,
                id_pais: 233,
                cad_nombre_es: "Uruguay".to_string(),
            },
            CountryData {
                idalpha3: "UZB".to_string(),
                idalpha2: "UZ".to_string(),
                tiene_edos: 0,
                id_pais: 234,
                cad_nombre_es: "Uzbekistán".to_string(),
            },
            CountryData {
                idalpha3: "VUT".to_string(),
                idalpha2: "VU".to_string(),
                tiene_edos: 0,
                id_pais: 235,
                cad_nombre_es: "Vanuatu".to_string(),
            },
            CountryData {
                idalpha3: "VAT".to_string(),
                idalpha2: "VA".to_string(),
                tiene_edos: 1,
                id_pais: 236,
                cad_nombre_es: "Vaticano".to_string(),
            },
            CountryData {
                idalpha3: "VEN".to_string(),
                idalpha2: "VE".to_string(),
                tiene_edos: 1,
                id_pais: 237,
                cad_nombre_es: "Venezuela".to_string(),
            },
            CountryData {
                idalpha3: "VNM".to_string(),
                idalpha2: "VN".to_string(),
                tiene_edos: 1,
                id_pais: 238,
                cad_nombre_es: "Vietnam".to_string(),
            },
            CountryData {
                idalpha3: "WLF".to_string(),
                idalpha2: "WF".to_string(),
                tiene_edos: 0,
                id_pais: 241,
                cad_nombre_es: "Wallis - Futuna".to_string(),
            },
            CountryData {
                idalpha3: "YEM".to_string(),
                idalpha2: "YE".to_string(),
                tiene_edos: 0,
                id_pais: 243,
                cad_nombre_es: "Yemen".to_string(),
            },
            CountryData {
                idalpha3: "DJI".to_string(),
                idalpha2: "DJ".to_string(),
                tiene_edos: 0,
                id_pais: 59,
                cad_nombre_es: "Yibuti".to_string(),
            },
            CountryData {
                idalpha3: "ZAR".to_string(),
                idalpha2: "ZR".to_string(),
                tiene_edos: 0,
                id_pais: 252,
                cad_nombre_es: "Zaire".to_string(),
            },
            CountryData {
                idalpha3: "ZMB".to_string(),
                idalpha2: "ZM".to_string(),
                tiene_edos: 0,
                id_pais: 245,
                cad_nombre_es: "Zambia".to_string(),
            },
            CountryData {
                idalpha3: "ZWE".to_string(),
                idalpha2: "ZW".to_string(),
                tiene_edos: 0,
                id_pais: 246,
                cad_nombre_es: "Zimbabwe".to_string(),
            },
        ]
    })
}
